### PR TITLE
diff() does not create unnecessary empty objects

### PR DESCRIPTION
**Pull request by bessarabov**

### CODE REVIEW

**Comment by sojiro14** [comment]
Sorry, I'm late.

Exactly your point is right. It's my fault. Thank you for your pull-request!!

But if I merged this pull-request, the following test case will be failed.

```
+{ source => '{"a":{},"c":"e"}', target => '{"a":"b","c":"d"}', expected => {'a'=>{}, 'c'=>'e'} }
```

I don't know how I should resolve this problem...

I'll consider how I resolve it.

**Comment by bessarabov** [comment]
Thank you! I've added this test (and one more) and updated the code to make tests pass.

**Comment by sojiro14** [comment]
@bessarabov 
Thank you for your pull request!!
I'm merging this pull request and versioning up this module with refactoring.

**Comment by bessarabov** [comment]
Super! Thank you! =)

**Pull request merged**
